config/routes.rb
Rails.application.routes.draw do

  resources :regions
  
  resources :animals do
    resources :sightings
  end

  root "animals#index"

end

app/models/animal.rb
class Animal < ActiveRecord::Base
  has_many :sightings, dependent: :destroy
  validates :name, presence: true
end

app/models/region.rb
class Region < ActiveRecord::Base
  has_many :animals
end

app/models/sighting.rb
class Sighting < ActiveRecord::Base
  belongs_to :animal
  belongs_to :region
  validates :date, presence: true

end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController

  #ISNECUD

  def index
    @animals = Animal.all.order("created_at DESC")
  end

  def show
    @animal = Animal.find(params[:id])
    @sighting = Sighting.new
  end

  def new
    @animal = Animal.new
  end

  def edit
    @animal = Animal.find(params[:id])
  end

  def create
    @animal = Animal.new(animal_params)
    if @animal.save
      redirect_to @animal
    else
      render 'new'
    end
  end

  def update

    @animal = Animal.find(params[:id])
    if @animal.update(params[:animal].permit(:name))
      redirect_to @animal, notice: "updated '#{@animal.name}' successfully"
    else
      render 'edit'
    end
  end

  def destroy

    @animal = Animal.find(params[:id])
    if @animal.destroy
      redirect_to root_path, notice: "deleted '#{@animal.name}' successfully"
    else
      render 'show'
    end
  end

  private

  def animal_params
    params.require(:animal).permit(:name)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/regions_controller.rb
class RegionsController < ApplicationController
  before_action :set_region, only: [:show, :edit, :update, :destroy]

  # GET /regions
  # GET /regions.json
  def index
    @regions = Region.all
  end

  # GET /regions/1
  # GET /regions/1.json
  def show
  end

  # GET /regions/new
  def new
    @region = Region.new
  end

  # GET /regions/1/edit
  def edit
  end

  # POST /regions
  # POST /regions.json
  def create
    @region = Region.new(region_params)

    respond_to do |format|
      if @region.save
        format.html { redirect_to @region, notice: 'Region was successfully created.' }
        format.json { render :show, status: :created, location: @region }
      else
        format.html { render :new }
        format.json { render json: @region.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /regions/1
  # PATCH/PUT /regions/1.json
  def update
    respond_to do |format|
      if @region.update(region_params)
        format.html { redirect_to @region, notice: 'Region was successfully updated.' }
        format.json { render :show, status: :ok, location: @region }
      else
        format.html { render :edit }
        format.json { render json: @region.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /regions/1
  # DELETE /regions/1.json
  def destroy
    @region.destroy
    respond_to do |format|
      format.html { redirect_to regions_url, notice: 'Region was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_region
      @region = Region.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def region_params
      params.require(:region).permit(:name)
    end
end

app/controllers/sightings_controller.rb
class SightingsController < ApplicationController

  # ISNECUD

  def index
    @sightings = Sighting.all
    @sighting = @animal.sightings.find(params[:id])
  end

  def show
    @animal = Animal.find(params[:animal_id])
    @sighting = @animal.sightings.find(params[:id])
  end

  def new
    @animal = Animal.find(params[:animal_id])
    @sighting = @animal.sightings.new

  end

  def edit
    @animal = Animal.find(params[:animal_id])
    @sighting = @animal.sightings.find(params[:id])
  end

  def create
    @animal = Animal.find(params[:animal_id])
    @sighting = @animal.sightings.create(params[:sighting].permit(:date, :latitude, :longitude, :region_id))
    @sighting = Sighting.new(sighting_params)
    if @sighting.save
      redirect_to animal_path(@animal), notice: "Succesfully created sighting for date of: '#{@sighting.date}'"
    else
      render 'new'
    end
  end

  def update
    @animal = Animal.find(params[:animal_id])
    @sighting = @animal.sightings.find(params[:id])
    if @sighting.update(params[:sighting].permit(:date, :latitude, :longitude))
      redirect_to @animal.sighting, notice: "succesfully updated sighting for date of '#{@sighting.date}'"
    else
      render 'edit'
    end
  end

  def destroy
    @animal = Animal.find(params[:animal_id])
    @sighting = @animal.sightings.find(params[:id])
    @sighting.destroy
    redirect_to animal_path(@animal), notice: "Succesfully deleted sighting for date of: '#{@sighting.date}'"
  end

  private

  def sighting_params
    params.require(:sighting).permit(:date, :latitude, :longitude)
  end

end

app/helpers/animals_helper.rb
module AnimalsHelper
  def error_messages_on obj, field
  obj.errors.messages[field].join '; ' if obj.errors.messages[field]
end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/sightings_helper.rb
module SightingsHelper
end

app/views/animals/_form.html.erb
<%= form_for @animal do |f| %>
	<% if @animal.errors.any? %>
		<div id="errors">
			<h2><%= pluralize(@animal.errors.count, "error") %> prevented this animal from saving:</h2>
				<ul>
					<% @animal.errors.full_messages.each do |msg| %>
						<li><%= msg %></li>
					<% end %>
				</ul>
		</div>
	<% end %>
		<%= f.label :name %><br>
		<%= f.text_field :name, :placeholder => "required *" %><br>
	<br>
		<%= f.submit %>
<% end %>

app/views/animals/edit.html.erb
<h1> Edit this Animal's name? </h1>

<%= render 'form' %>
<!-- <%= link_to "Back", root_path, class: "button "%> -->

<button type="button"><%= link_to "Back", root_path %></button>

<!-- <FORM METHOD="LINK" ACTION= root_path  >
<INPUT TYPE="submit" VALUE="Clickable Button">
</FORM> -->

app/views/animals/index.html.erb
<div align="center">

  <div id="wrapper">
    <h1>
      <div id="first">
        Animals index
      </div>
      <div align="right">
            <%= link_to 'New Animal', new_animal_path %>
      </div>
    </h1>
  </div>

  <p id="notice"><%= notice %></p>

  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th colspan="3"></th>
      </tr>
    </thead>
  </table>

  <br>
  <% @animals.each do |animal| %>

  <div id="div1">
    <%= link_to animal.name, "/animals/#{animal.id}", class: "button"  %>
  </div>
  &mdash;
  <div id="div1">
    <p class="animal_time"><%= time_ago_in_words(animal.created_at) %> Ago &mdash;</p>
  </div>
  <div id="div1">
    <%= button_to "Delete me.", "/animals/#{animal.id}", method: 'delete', class: "button", data: { confirm: 'Are you sure?' }  %>
  </div>
  <hr width ="75%">
  <% end %>

</div>

app/views/animals/new.html.erb
<h1> new post</h1>

<%= render 'form' %>

<br>

<button type="button"><%= link_to 'Back to Home', root_path %></button>

app/views/animals/show.html.erb
<p id="notice"><%= notice %></p>

<div id="animal_content">

  <h1 class ="name">
    <%= @animal.name %>:
    was submitted <%= time_ago_in_words(@animal.created_at) %> ago
    <div align="right">
      <button type="button"><%= link_to "Edit #{@animal.name}", edit_animal_path(@animal)%></button> |
      <button type="button"><%= link_to 'Back to Home', root_path %></button>
    </div>
  </h1>

  <!-- <p class="date"></p> -->

  <div id="sighting" >
    <div ="div1">
      <h2><%= @animal.sightings.count %> sightings for this animal |
      <%= link_to "Add a new sighting", new_animal_sighting_path( @animal) %></h2>
    </div>

    <%= render @animal.sightings.order("created_at DESC") %>

  </div>.

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>



  <title>Playground</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body >

  <%= yield %>

</body>
</html>

app/views/regions/_form.html.erb
<% if @region.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@region.errors.count, "error") %> prohibited this region from being saved:</h2>

    <ul>
    <% @region.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for(@region) do |f| %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/regions/edit.html.erb
<h1>Editing Region</h1>

<%= render 'form' %>

<%= link_to 'Show', @region %> |
<%= link_to 'Back', regions_path %>

app/views/regions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Regions</h1>

<table>
  <thead>
    <tr>
      <th>String</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @regions.each do |region| %>
      <tr>
        <td><%= region.name %></td>
        <td><%= link_to 'Show', region %></td>
        <td><%= link_to 'Edit', edit_region_path(region) %></td>
        <td><%= link_to 'Destroy', region, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Region', new_region_path %>

app/views/regions/new.html.erb
<h1>New Region</h1>

<%= render 'form' %>

<%= link_to 'Back', regions_path %>

app/views/regions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @region.name %>
</p>

<%= link_to 'Edit', edit_region_path(@region) %> |
<%= link_to 'Back', regions_path %>

app/views/sightings/_form.html.erb
<%= form_for([@animal, @sighting]) do |f| %>

	<% if @sighting.errors.any? %>

		<div id="errors">
				<h2><%= pluralize(@sighting.errors.count, "error") %> prevented this sighting from saving:</h2>
				<ul>
					<% @sighting.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
					<% end %>
				</ul>
		</div>
		<% end %>

	<div class="field" >
			<%= f.label :date %><br>
			<%= f.text_field :date %><br>
		<br>
			<%= f.label :latitude %><br>
			<%= f.text_area :latitude %><br>
		<br>
			<%= f.label :longitude %><br>
			<%= f.text_area :longitude %><br>
		<br>
	</div>

	<div class="actions" >
		<%= f.collection_select :region_id, Region.all, :id, :name%>
		<%= f.submit %>
	</div>

<% end %>

<button type="button"><%= link_to 'Back to Home', root_path %></button>

app/views/sightings/_sighting.html.erb
<div class="sighting clearfix">

	<div class="sighting_content">

		<div class="container">
			Date of:
				<p class="sighting_date"><strong><%= sighting.date %></strong></p></div>
			<div class="container">
			Latitude:
				<p class="sighting_latitude"><strong><%= sighting.latitude %></strong></p></div>
			<div class="container">
			Longitude:
				<p class="sighting_longitude"><strong><%= sighting.longitude %></strong></p></div>
			<div class="container">
			Region:
				<p class="sighting_region"><strong><%= sighting.region %></strong></p></div>

	</div>

		<div class="container">
			<p> <%= link_to "Delete", animal_sighting_path(@animal, sighting), method: :delete, class: "button",
			data: { confirm: 'Are you sure?' }  %></p> |
			<p> <%= link_to "Edit", edit_animal_sighting_path(sighting.animal, sighting), class: "button" %></p>
		</div>

</div>

app/views/sightings/edit.html.erb
<h1> Edit page for sightings </h1>

<%= render 'form' %>

<button type="button"><%= link_to "Back", root_path %></button>

app/views/sightings/new.html.erb
new sighting page

<%= render 'form' %>

app/views/sightings/show.html.erb
<p id="notice"><%= notice %></p>

<%= render "form" %>



<p>
  <strong>Date of sighting:</strong>
  <%= @sighting.date %>
</p>
<p>
  <strong>Latitude at sighting:</strong>
  <%= @sighting.latitude %>
</p>
<p>
  <strong>Longitude at sighting:</strong>
  <%= @sighting.longitude %>
</p>

<p>
  <strong>Region of sighting:</strong>
  <%= @sighting.region %>
</p>

just making sure this is my show page for a sighting
<br><br>




<%= link_to 'Back', root_path, class: "button" %>
<br>
<br>
<br>
<br>
<br>
<br>
<br>